$(document).ready(function(){
	$(".asset").on("click",function(){
		$(".showZ").show();
		$(".shadow").show();
	})
	$(".hideIcon").on("click",function(){
		$(".showZ").hide();
		$(".shadow").hide();
	})
	$(".sum").on("click",function(){
		$(".pop").show();
		$(".shadow").show();
	})
	$(".hideTz").on("click",function(){
		$(".pop").hide();
		$(".shadow").hide();
	})
	$(".ur").on("click",function(){
		$(".code-up").show()
		$(".pop").hide()		
	})
	$(".shut").on('click',function(){
		$(".code-up").hide();
		$(".shadow").hide();
	})
})
